export { scan } from './discovery.js';
export { AppleTV, Key, TextInputActionType } from './appletv.js';
export type { KeyboardInfo, TextInputEvent, CompanionEvent } from './appletv.js';
export { CompanionConnection } from './companion/connection.js';
export { CompanionAPI, CompanionMessageType } from './companion/api.js';
export type { CompanionTransport, RemoteSessionOptions } from './companion/api.js';
export { CompanionPairSetup } from './companion/pair-setup.js';
export { CompanionSession } from './companion/companion-session.js';
export { opackEncode, opackDecode } from './companion/opack.js';
export type { OpackValue, OpackDict } from './companion/opack.js';
export { FrameType, encodeFrame, parseFrames } from './companion/framing.js';
export type { Frame } from './companion/framing.js';
export { Credentials, parseCredentials } from './credentials.js';
export { NowPlayingInfo, PlaybackState } from './now-playing-info.js';
export { SupportedCommand, Command } from './supported-command.js';
export { Message } from './message.js';
export { AirPlayConnection } from './connection.js';
export type { HAPCredentials } from './auth/types.js';
export type { ScanOptions, DiscoveredDevice } from './discovery.js';
